### ISSUE TITLE
Ansible.cfg not being loaded

### ISSUE THREAD

**Issue by darthVikes** [ansible/ansible-rulebook#454]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/ansible-rulebook/issues) for duplicates.
- [X] I understand that ansible-rulebook is open source software provided for free and that I might not receive a timely response.

### Bug Summary

ansible.cfg seems to only be pulled if you use update /etc/ansible/ansible.cfg

When add ansible.cfg into the CWD, or via export ANSIBLE_CONFIG=./ansible.cfg it does not load the correct ansible.cfg information

### Environment

Rocky 9.1

ansible-rulebook --version
__version__ = '0.11.0'
  Executable location = /usr/local/bin/ansible-rulebook
  Drools_jpy version = 0.2.5
  Java home = /usr/lib/jvm/java-17-openjdk-17.0.6.0.10-3.el9_1.x86_64
  Java version = 17.0.6
  Python version = 3.9.14 (main, Nov  7 2022, 00:00:00) [GCC 11.3.1 20220421 (Red Hat 11.3.1-2)]

### Steps to reproduce

create a new working directory

mkdir /opt/ansible
vi ansible.cfg
[defaults]
# paths to search for roles in, colon separated
library        = ./library
collections_path = ./collections
roles_path = ./roles

vi  kafka-playbook.yml
---
- name: Read messages from a kafka topic and act on them
  hosts: localhost

  ## Define our source for events
  sources:
    - ansible.eda.kafka:
        host: localhost
        port: 9092
        topic: eda-topic
        group_id:

  ## Define the conditions we are looking for
  rules:
    - name: Say Hello
      condition: event.message == "Ansible is cool"
      ## Define the action we should take should the condition be met
      action:
        run_playbook:
          name: playbook.yml
          verbosity: 4

vi playbook.yml
- name: HelloWorld
  hosts: localhost
  connection: local
  roles:
    - helloworld

mkdir -p ./roles/helloworld/tasks
vi ./roles/helloworld/tasks/main.yml
---
# tasks file for HelloWorld
- name: debug HelloWorld myvariable
  debug:
    msg: "{{ myvariable }}"

mkdir -p ./roles/helloworld/vars
vi ./roles/helloworld/vars/main.yml
---
# vars file for HelloWorld
myvariable: "Hello World!

inventory.yaml
all:
  hosts:
    localhost:
      ansible_connection: local

.
├── ansible.cfg
├── inventory.yml
├── kafka-playbook.yml
├── playbook.yml
└── roles
    └── helloworld
        ├── tasks
        │   └── main.yml
        └── vars
            └── main.yml

ansible-galaxy collection install ansible.eda
export ANSIBLE_CONFIG=./ansible.cfg
echo $ANSIBLE_CONFIG
./ansible.cfg
ansible-rulebook --verbose --inventory inventory.yml --rulebook kafka-playbook.yml

So not quite sure if this isa ansible-rulebook issue as it i believe is calling ansible-playbook or if its an ansible-playbook issue and if this needs to be open here or ansible-playbook repo?

### Actual results

ansible-rulebook --verbose --inventory inventory.yml --rulebook kafka-playbook.yml
2023-03-17 15:58:43,075 - ansible_rulebook.app - INFO - Starting sources
2023-03-17 15:58:43,075 - ansible_rulebook.app - INFO - Starting rules
2023-03-17 15:58:43,075 - ansible_rulebook.engine - INFO - run_ruleset
2023-03-17 15:58:43,792 - ansible_rulebook.engine - INFO - ruleset define: {"name": "Read messages from a kafka topic and act on them", "hosts": ["localhost"], "sources": [{"EventSource": {"name": "ansible.eda.kafka", "source_name": "ansible.eda.kafka", "source_args": {"host": "localhost", "port": 9092, "topic": "eda-topic", "group_id": null}, "source_filters": []}}], "rules": [{"Rule": {"name": "Say Hello", "condition": {"AllCondition": [{"EqualsExpression": {"lhs": {"Event": "message"}, "rhs": {"String": "Ansible is cool"}}}]}, "actions": [{"Action": {"action": "run_playbook", "action_args": {"name": "playbook.yml", "verbosity": 4}}}], "enabled": true}}]}
2023-03-17 15:58:43,808 - ansible_rulebook.engine - INFO - load source
2023-03-17 15:58:44,526 - ansible_rulebook.engine - INFO - load source filters
2023-03-17 15:58:44,527 - ansible_rulebook.engine - INFO - Calling main in ansible.eda.kafka
2023-03-17 15:58:44,527 - aiokafka.consumer.subscription_state - INFO - Updating subscribed topics to: frozenset({'eda-topic'})
2023-03-17 15:58:44,531 - ansible_rulebook.engine - INFO - Waiting for all ruleset tasks to end
2023-03-17 15:58:44 531 [drools-async-evaluator-thread] INFO org.drools.ansible.rulebook.integration.api.io.RuleExecutorChannel - Async channel connected
2023-03-17 15:58:44,532 - ansible_rulebook.rule_set_runner - INFO - Waiting for actions on events from Read messages from a kafka topic and act on them
2023-03-17 15:58:44,533 - ansible_rulebook.rule_set_runner - INFO - Waiting for events, ruleset: Read messages from a kafka topic and act on them
2023-03-17 15:58:44,538 - aiokafka.consumer.group_coordinator - INFO - Metadata for topic has changed from {} to {'eda-topic': 1}.
2023-03-17 15:58:52 553 [main] INFO org.drools.ansible.rulebook.integration.api.rulesengine.RegisterOnlyAgendaFilter - Activation of effective rule "Say Hello" with facts: [Event DROOLS_PROTOTYPE with values = {message=Ansible is cool}]
2023-03-17 15:58:52,566 - ansible_rulebook.rule_generator - INFO - calling Say Hello
2023-03-17 15:58:52,567 - ansible_rulebook.rule_set_runner - INFO - call_action run_playbook
2023-03-17 15:58:52,567 - ansible_rulebook.rule_set_runner - INFO - substitute_variables [{'name': 'playbook.yml', 'verbosity': 4}] [{'event': {'message': 'Ansible is cool'}}]
2023-03-17 15:58:52,567 - ansible_rulebook.rule_set_runner - INFO - action args: {'name': 'playbook.yml', 'verbosity': 4}
2023-03-17 15:58:52,567 - ansible_rulebook.builtin - INFO - running Ansible playbook: playbook.yml
2023-03-17 15:58:52,570 - ansible_rulebook.builtin - INFO - ruleset: Read messages from a kafka topic and act on them, rule: Say Hello
2023-03-17 15:58:52,570 - ansible_rulebook.builtin - INFO - Calling Ansible runner
ansible-playbook [core 2.14.3]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.9.14 (main, Nov  7 2022, 00:00:00) [GCC 11.3.1 20220421 (Red Hat 11.3.1-2)] (/usr/bin/python)
  jinja version = 3.1.2
  libyaml = True
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /tmp/run_playbookl9sh3_nm/inventory/hosts as it did not pass its verify_file() method
script declined parsing /tmp/run_playbookl9sh3_nm/inventory/hosts as it did not pass its verify_file() method
auto declined parsing /tmp/run_playbookl9sh3_nm/inventory/hosts as it did not pass its verify_file() method
Set default localhost to localhost
Parsed /tmp/run_playbookl9sh3_nm/inventory/hosts inventory source with yaml plugin
ERROR! the role 'helloworld' was not found in /tmp/run_playbookl9sh3_nm/project/roles:/root/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/tmp/run_playbookl9sh3_nm/project

The error appears to be in '/tmp/run_playbookl9sh3_nm/project/playbook.yml': line 5, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
    - helloworld
      ^ here
2023-03-17 15:58:53,861 - ansible_rulebook.builtin - INFO - Ansible Runner Queue task cancelled
2023-03-17 15:58:53,864 - ansible_rulebook.builtin - INFO - Playbook rc: 1, status: failed
2023-03-17 15:58:53,865 - ansible_rulebook.builtin - ERROR - ansible-playbook [core 2.14.3]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.9.14 (main, Nov  7 2022, 00:00:00) [GCC 11.3.1 20220421 (Red Hat 11.3.1-2)] (/usr/bin/python)
  jinja version = 3.1.2
  libyaml = True
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /tmp/run_playbookl9sh3_nm/inventory/hosts as it did not pass its verify_file() method
script declined parsing /tmp/run_playbookl9sh3_nm/inventory/hosts as it did not pass its verify_file() method
auto declined parsing /tmp/run_playbookl9sh3_nm/inventory/hosts as it did not pass its verify_file() method
Set default localhost to localhost
Parsed /tmp/run_playbookl9sh3_nm/inventory/hosts inventory source with yaml plugin
ERROR! the role 'helloworld' was not found in /tmp/run_playbookl9sh3_nm/project/roles:/root/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/tmp/run_playbookl9sh3_nm/project

The error appears to be in '/tmp/run_playbookl9sh3_nm/project/playbook.yml': line 5, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
    - helloworld
      ^ here

### Expected results

2023-03-17 15:58:53,865 - ansible_rulebook.builtin - ERROR - ansible-playbook [core 2.14.3]
  config file = /etc/ansible/ansible.cfg

this should be taking it from my environment variable $ANSIBLE_CONFIG=./ansible.cfg
which is not the location above shown

If I edit /etc/ansible/ansible.cfg then I can get it working by pointing it to my CWD in /opt/ansible

**Comment by Alex-Izquierdo** [comment]
Hi @darthVikes This is the same issue explained in https://github.com/ansible/event-driven-ansible/issues/100

ansible-rulebook doesn't take care of other files relative to the project and only takes the inventory and the playbook. The playbook must be executed from a collection and/or the ANSIBLE_CONFIG variable must have an absolute path.

**Comment by darthVikes** [comment]
used FQDN for ANSIBLE_CONFIG
